"""
Turns the Excel files + config.py into the AMPL .dat files the MIQP reads.

Run this before any MIQP. It writes:
    ampl/oyster_quad_M{1,2}_{constant,realistic}.dat   <- one per matrix + P0 mode
    ampl/oyster_comm.dat                               <- community sets
    ampl/oyster_size.dat                               <- reef size bounds

    python -m scripts.prepare_data              # all 4 combos
    python -m scripts.prepare_data --matrix 1
    python -m scripts.prepare_data --p0 realistic

Heads up on indexing: AMPL uses 0..48, which are POSITIONS in
config.CANDIDATE_SITES, not the real site labels. Everything written here is in
AMPL index space. The mapping is saved to runs/ so you can translate back.
"""
import argparse

import numpy as np
import pandas as pd

import config
from src.model.jars_ode import setP0

# site label -> AMPL index
LAB2IDX = {int(lab): i for i, lab in enumerate(config.CANDIDATE_SITES)}
N = len(config.CANDIDATE_SITES)


def load_matrix(matrix_id):
    """Read a connectivity xlsx, drop the sites we don't want, return (labels, P1)."""
    key = config.matrix_key(matrix_id)
    arr = pd.read_excel(config.MATRICES[key], header=None).values
    labels = arr[0, 1:].astype(int)
    P = arr[1:, 1:].astype(float)

    keep = ~np.isin(labels, config.UNWANTED)
    labels, P = labels[keep], P[np.ix_(keep, keep)]

    # if this ever fires, the xlsx and config disagree about the candidate list
    assert np.array_equal(labels, config.CANDIDATE_SITES), \
        f"matrix {matrix_id}: sites in the xlsx don't match config.CANDIDATE_SITES"

    return labels, P * config.P1SCALING


def write_quad(matrix_id, p0_mode):
    """Write N, K, Pe and W for one (matrix, P0 mode)."""
    labels, P1 = load_matrix(matrix_id)

    # W[l,k] = larvae going l -> k, with every source frozen at A_STAR.
    # The diagonal stays: a reef feeds itself, same as the ODE.
    W = P1 * (config.A_STAR ** config.ALPHA)

    # constant = everyone gets the same external supply (isolates the network).
    # realistic = the low/moderate/high classes from VOSARA.
    Pe = (np.full(N, config.CONST_P0) if p0_mode == "constant"
          else setP0(labels).astype(float))

    out = config.quad_dat(matrix_id, p0_mode)
    lines = [f"# generated by prepare_data.py -- matrix {matrix_id}, P0 = {p0_mode}",
             "# indices are positions in config.CANDIDATE_SITES, NOT site labels", "",
             "set N :="]
    lines += [f"  {i}" for i in range(N)]
    lines += [";", "", f"param K := {config.K};", "", "param Pe :="]
    lines += [f"  {i} {Pe[i]:.6f}" for i in range(N)]
    lines += [";", "", "param W :="]
    lines += [f"  [{i}, {j}] {W[i, j]:.6f}"
              for i in range(N) for j in range(N) if W[i, j] != 0]
    lines += [";", ""]
    out.write_text("\n".join(lines), encoding="utf-8")

    diag = int((np.diag(W) != 0).sum())
    print(f"  wrote {out.name}  ({diag} self-recruitment entries kept)")

    # so you can turn AMPL indices back into site labels later
    config.RUNS_DIR.mkdir(exist_ok=True)
    pd.DataFrame({"index": np.arange(N), "site_id": labels}).to_csv(
        config.mapping_csv(matrix_id), index=False)


def write_comm():
    """Community sets. The xlsx lists site LABELS, AMPL wants indices, so translate."""
    raw = pd.read_excel(config.COMMUNITIES_XLSX, header=None).values
    comms = {}
    for r in range(1, raw.shape[0]):
        if pd.isna(raw[r, 0]):
            continue
        cnum, size = int(raw[r, 0]), int(raw[r, 1])
        labs = [int(v) for v in raw[r, 2:] if not pd.isna(v)]
        assert len(labs) == size, f"C{cnum}: says {size} sites but lists {len(labs)}"
        comms[cnum] = sorted(labs)

    # the communities have to be a clean partition of the 49 candidates, or the
    # MIQP is quietly solving a different problem than you think
    flat = [l for v in comms.values() for l in v]
    assert len(flat) == len(set(flat)), "a site is in two communities"
    assert set(flat) == set(int(s) for s in config.CANDIDATE_SITES), \
        "communities don't cover exactly the 49 candidates"

    lines = ["# generated by prepare_data.py from " + config.COMMUNITIES_XLSX.name,
             "# these are AMPL INDICES, not site labels", ""]
    for c in sorted(comms):
        lines.append(f"# C{c} = {config.COMM_NAMES[c]}: sites {comms[c]}")
        lines.append(f"set C{c} :=")
        lines += [f"  {LAB2IDX[l]}" for l in comms[c]]
        lines += [";", ""]
    lines += [f"param rmin{c} := {config.COMMUNITY_MINS[c]};" for c in sorted(comms)]
    lines.append("")
    config.COMM_DAT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {config.COMM_DAT.name}  "
          f"(sizes {[len(comms[c]) for c in sorted(comms)]}, partition OK)")
    return comms


def write_size():
    """Reef size bounds. Note U is tiered by index -- that's from the original
    testbed, not biology. size_sweep.py redoes it with uniform bounds."""
    s = config.SIZE
    lines = ["# generated by prepare_data.py from config.SIZE", "", "param L :="]
    lines += [f"  {i} {s['L']:.6f}" for i in range(N)]
    lines += [";", "", "param U :="]
    lines += [f"  {i} {(s['U_FIRST'] if i < s['U_SPLIT'] else s['U_REST']):.6f}"
              for i in range(N)]
    lines += [";", "", f"param TotReefSize := {s['TotReefSize']:.2f};", "",
              f"param Sbar := {s['Sbar']:g};", ""]
    config.SIZE_DAT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {config.SIZE_DAT.name}  "
          f"(L={s['L']:g}, U={s['U_FIRST']:g}/{s['U_REST']:g}, T={s['TotReefSize']:g})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--matrix", choices=["1", "2", "both"], default="both")
    ap.add_argument("--p0", choices=["constant", "realistic", "both"], default="both")
    args = ap.parse_args()

    config.AMPL_DIR.mkdir(exist_ok=True)
    config.RUNS_DIR.mkdir(exist_ok=True)

    print("communities + sizes (same for every matrix):")
    write_comm()
    write_size()

    mats = ["1", "2"] if args.matrix == "both" else [args.matrix]
    modes = ["constant", "realistic"] if args.p0 == "both" else [args.p0]
    print("\nconnectivity:")
    for m in mats:
        for mode in modes:
            write_quad(m, mode)

    print("\ndone")


if __name__ == "__main__":
    main()