# scripts/prepare_data.py
#
# ONE place that turns the raw inputs (a connectivity .xlsx + the communities
# .xlsx) plus config.py into the three AMPL data files the MIQP models read:
#
#     ampl/oyster_quad.dat   N, K, Pe, W           (base surrogate weights)
#     ampl/oyster_comm.dat   C1..C5 + rmin1..5     (communities + minimums)
#     ampl/oyster_size.dat   L, U, TotReefSize, Sbar
#
# It also writes the AMPL-index <-> site-label mapping and a W preview, and it
# REFUSES to run if the communities do not partition the 49 candidates. This is
# what makes the community data impossible to silently break again: it is always
# derived (with the label->index translation) and always verified.
#
# Every number comes from config.py. To experiment, edit config.py and re-run:
#
#     python -m scripts.prepare_data --matrix 1
#     python -m scripts.prepare_data --matrix both     # default
#
# (Previously this was prepare_miqp_data.py, which only wrote oyster_quad.dat and
# left oyster_comm.dat / oyster_size.dat to be hand-maintained -- the source of
# the stale, untranslated community file.)

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

import config

LAB2IDX = {int(lab): i for i, lab in enumerate(config.CANDIDATE_SITES)}
N_SITES = len(config.CANDIDATE_SITES)


# --------------------------------------------------------------------------- #
# Connectivity -> base surrogate (oyster_quad.dat)
# --------------------------------------------------------------------------- #
def load_matrix(matrix_id: str):
    """Read a connectivity .xlsx, drop UNWANTED, return (labels, P) in candidate
    order. Asserts the kept labels match CANDIDATE_SITES exactly."""
    key = config.matrix_key(matrix_id)
    arr = pd.read_excel(config.MATRICES[key], header=None).values
    labels = arr[0, 1:].astype(int)
    P = arr[1:, 1:].astype(float)

    mask = ~np.isin(labels, config.UNWANTED)
    labels = labels[mask]
    P = P[np.ix_(mask, mask)]

    if not np.array_equal(labels, config.CANDIDATE_SITES):
        raise ValueError(
            f"matrix {matrix_id}: kept labels do not match config.CANDIDATE_SITES "
            f"(got {labels.tolist()})"
        )
    return labels, P


def write_quad_dat(matrix_id: str) -> int:
    labels, P = load_matrix(matrix_id)
    n = len(labels)

    P = P * config.P1SCALING
    W = P * (config.A_STAR ** config.ALPHA)         # self-recruitment KEPT (diagonal intact)
    Pe = config.CONST_P0 * np.ones(n)

    # mapping + preview (in site labels)
    config.RUNS_DIR.mkdir(exist_ok=True)
    pd.DataFrame({"index": np.arange(n), "site_id": labels}).to_csv(
        config.RUNS_DIR / f"oyster_index_mapping_matrix{matrix_id}.csv", index=False)
    pd.DataFrame(W, index=labels, columns=labels).to_csv(
        config.RUNS_DIR / f"oyster_data_preview_matrix{matrix_id}.csv")

    out = config.AMPL_DIR / "oyster_quad.dat"
    lines = [f"# auto-generated by scripts/prepare_data.py (matrix {matrix_id})",
             "# self-recruitment (diagonal) retained, matching the JARS ODE", "",
             "set N :="]
    lines += [f"  {i}" for i in range(n)]
    lines += [";", "", f"param K := {config.K};", "", "param Pe :="]
    lines += [f"  {i} {Pe[i]:.4f}" for i in range(n)]
    lines += [";", "", "param W :="]
    diag = 0
    for i in range(n):
        for j in range(n):
            if W[i, j] != 0.0:
                lines.append(f"  [{i}, {j}] {W[i, j]:.6f}")
                if i == j:
                    diag += 1
    lines += [";", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[prepare] wrote {out}  ({diag} diagonal entries kept)")
    return diag


# --------------------------------------------------------------------------- #
# Communities (oyster_comm.dat)  -- the formerly-broken file
# --------------------------------------------------------------------------- #
def read_communities() -> dict:
    """Parse config.COMMUNITIES_XLSX into {comm_number: [site_label, ...]}.
    Layout per row: comm_number | size | label_1 label_2 ..."""
    raw = pd.read_excel(config.COMMUNITIES_XLSX, header=None).values
    comms = {}
    for r in range(1, raw.shape[0]):
        if pd.isna(raw[r, 0]):
            continue
        cnum = int(raw[r, 0]); size = int(raw[r, 1])
        labs = [int(v) for v in raw[r, 2:] if not pd.isna(v)]
        if len(labs) != size:
            raise ValueError(f"C{cnum}: stated size {size} != {len(labs)} labels listed")
        comms[cnum] = sorted(labs)
    return comms


def verify_partition(comms: dict) -> None:
    cand = set(int(s) for s in config.CANDIDATE_SITES)
    flat = [l for labs in comms.values() for l in labs]
    seen = set(flat)
    dupes   = sorted(x for x in seen if flat.count(x) > 1)
    extra   = sorted(seen - cand)
    missing = sorted(cand - seen)
    if dupes or extra or missing:
        raise ValueError(
            "communities do NOT partition the 49 candidates:\n"
            f"  duplicates              : {dupes or 'none'}\n"
            f"  in community not candidate: {extra or 'none'}\n"
            f"  candidate with no community: {missing or 'none'}")
    print(f"[prepare] community partition OK: {len(comms)} communities, "
          f"sizes {[len(comms[c]) for c in sorted(comms)]}, cover all {len(cand)} candidates")


def write_comm_dat() -> None:
    comms = read_communities()
    verify_partition(comms)

    out = config.AMPL_DIR / "oyster_comm.dat"
    lines = ["# auto-generated by scripts/prepare_data.py from data/communitiesJune2002.xlsx",
             "# values are AMPL INDICES (positions in CANDIDATE_SITES), NOT site labels",
             "# C1..C5 partition all 49 candidates; minimums rmin1..5 come from config", ""]
    for c in sorted(comms):
        idxs = sorted(LAB2IDX[l] for l in comms[c])
        lines.append(f"# C{c}: labels {comms[c]}")
        lines.append(f"set C{c} :=")
        lines += [f"  {i}" for i in idxs]
        lines += [";", ""]
    lines.append("# community minimums (config.COMMUNITY_MINS)")
    for c in sorted(config.COMMUNITY_MINS):
        lines.append(f"param rmin{c} := {config.COMMUNITY_MINS[c]};")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[prepare] wrote {out}")


# --------------------------------------------------------------------------- #
# Reef sizing (oyster_size.dat)
# --------------------------------------------------------------------------- #
def write_size_dat() -> None:
    s = config.SIZE
    out = config.AMPL_DIR / "oyster_size.dat"
    lines = ["# auto-generated by scripts/prepare_data.py from config.SIZE",
             "# matrix-independent (constants only)", "", "param L :="]
    lines += [f"  {i} {s['L']:.6f}" for i in range(N_SITES)]
    lines += [";", "", "param U :="]
    for i in range(N_SITES):
        u = s["U_FIRST"] if i < s["U_SPLIT"] else s["U_REST"]
        lines.append(f"  {i} {u:.6f}")
    lines += [";", "",
              f"param TotReefSize := {s['TotReefSize']:.2f};", "",
              f"param Sbar := {s['Sbar']:g};", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[prepare] wrote {out}")


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser(description="Generate all AMPL .dat files from config + xlsx.")
    ap.add_argument("--matrix", choices=["1", "2", "both"], default="both")
    args = ap.parse_args()

    config.AMPL_DIR.mkdir(exist_ok=True)
    config.RUNS_DIR.mkdir(exist_ok=True)

    # communities + sizing are matrix-independent -> write once
    write_comm_dat()
    write_size_dat()

    mats = ["1", "2"] if args.matrix == "both" else [args.matrix]
    for m in mats:
        print(f"\n[prepare] --- matrix {m} ---")
        write_quad_dat(m)
        # NOTE: oyster_quad.dat is overwritten per matrix; solve one matrix at a
        # time, or rely on run_everything.py which re-prepares before each matrix.

    print("\n[prepare] done.")


if __name__ == "__main__":
    main()
