# scripts/run_iterated.py
#
# Site-specific external supply: paper Tables 6 and 7.
#
# This is the one experiment nothing else covers. run_everything.py runs at
# constant Pe=170, where the frozen A_* is harmless: the external term is the
# same constant for every feasible 25-site set, and A_* only rescales the
# objective. Under realistic Pe in {100,200,400} neither holds.
#
#     python -m scripts.run_iterated                       # Tables 6 and 7
#     python -m scripts.run_iterated --exp astar           # Table 6 only
#     python -m scripts.run_iterated --exp iterated        # Table 7 only
#     python -m scripts.run_iterated --matrix 1 --fallback network
#
# MIQP goes through src/opt/miqp.py like every other script. Scoring goes through
# src/opt/evaluator.evaluate_subset, the same function run_everything.py uses
# (verified: it reproduces paper Table 3 to six decimals).
#
# Settings: config.ITER, config.A_STAR_SWEEP, config.BEST_HEUR_REAL.

import argparse
import csv
import time

import numpy as np
from scipy.integrate import solve_ivp

import config
from src.model.jars_ode import load_connectivity, setP0, odesys
from src.opt.evaluator import evaluate_subset
from src.opt.miqp import solve

ITER_DAT = config.AMPL_DIR / "oyster_iter.dat"   # rewritten before every solve


# --------------------------------------------------------------------------- #
# data
# --------------------------------------------------------------------------- #
def load(matrix_id):
    """(conn, key, labels, P1, Pe) for one matrix, candidates only."""
    conn, key = load_connectivity(config.MATRICES[config.matrix_key(matrix_id)])
    mask = ~np.isin(key, config.UNWANTED)
    labels = key[mask]
    P1 = conn[np.ix_(mask, mask)] * config.P1SCALING
    return conn, key, labels, P1, setP0(labels).astype(float)


def score(sites, conn, key, densities=False):
    """F(S) under realistic Pe, optionally with {site: adult density}."""
    return evaluate_subset(sites, conn, key, P0_mode="realistic",
                           return_densities=densities)


def single_reef(P1_ii, Pe_i):
    """One reef alone, given its own self-recruitment and external supply."""
    v0 = np.array([config.IC["J"], config.IC["A"], config.IC["R"], config.IC["S"]], float)
    sol = solve_ivp(lambda t, v: odesys(t, v, np.array([Pe_i]), np.array([[P1_ii]]),
                                        config.MU * np.ones(1)),
                    [0, config.TMAX], v0, method="RK45", rtol=1e-6)
    return max(float(sol.y[1, -1]), 0.0)


def isolated_A(labels, P1, Pe):
    """Abar_l: every candidate integrated ALONE, self-recruitment retained."""
    return np.array([single_reef(P1[i, i], Pe[i]) for i in range(len(labels))])


def lookahead_A(labels, P1, Pe, sel, dens):
    """Network-aware fallback: each candidate alone, but with external supply
    raised by the inflow it would get from the CURRENT selected set,
        Pe_l + sum_{j in S} P1[j,l] * A_j^ALPHA
    i.e. what it would reach if it joined S. Depends only on S, never on the
    optimal design, so it stays non-circular."""
    pos = {int(l): i for i, l in enumerate(labels)}
    j = np.array([pos[s] for s in sel])
    A_sel = np.maximum(np.array([dens[s] for s in sel]), 0.0)
    inflow = P1[j, :].T @ (A_sel ** config.ALPHA)
    return np.array([single_reef(P1[i, i], Pe[i] + inflow[i]) for i in range(len(labels))])


# --------------------------------------------------------------------------- #
# MIQP with per-source densities
# --------------------------------------------------------------------------- #
def solve_weighted(matrix_id, labels, P1, Pe, A):
    """Base surrogate with W[l,k] = P1[l,k] * A_l^ALPHA (A varies by source
    instead of being the single frozen A_*). Writes its own .dat because the
    weights change every pass, then solves through src/opt/miqp.py."""
    # clip: evaluate_subset does not clip, and a tiny negative A makes
    # A**1.72 = NaN, which would land in W and violate `param W{N,N} >= 0`.
    W = P1 * (np.maximum(np.asarray(A), 0.0) ** config.ALPHA)[:, None]
    n = len(labels)
    lines = ["# auto-generated by scripts/run_iterated.py",
             "# per-source A_l; self-recruitment (diagonal) retained", "", "set N :="]
    lines += [f"  {i}" for i in range(n)]
    lines += [";", "", f"param K := {config.K};", "", "param Pe :="]
    lines += [f"  {i} {Pe[i]:.6f}" for i in range(n)]
    lines += [";", "", "param W :="]
    lines += [f"  [{i}, {j}] {W[i, j]:.6f}"
              for i in range(n) for j in range(n) if W[i, j] != 0.0]
    lines += [";", ""]
    ITER_DAT.write_text("\n".join(lines), encoding="utf-8")
    return solve("base", matrix_id, dat_override=ITER_DAT)["sites"]


# --------------------------------------------------------------------------- #
# the iteration
# --------------------------------------------------------------------------- #
def iterate(matrix_id, A0, rule, Abar, labels, P1, Pe, conn, key):
    """solve -> one feedback ODE on the chosen set -> re-weight -> re-solve.
    Stops when the selected set repeats. `rule` is a config.ITER["rules"] value."""
    pos = {int(l): i for i, l in enumerate(labels)}
    A, seen = np.array(A0, float), []

    for t in range(config.ITER["max_passes"]):
        sel = solve_weighted(matrix_id, labels, P1, Pe, A)
        if sel in seen:
            return sel, t, score(sel, conn, key)
        seen.append(sel)

        F, dens = score(sel, conn, key, densities=True)      # the one feedback ODE

        if rule == "sticky":
            A_new = A.copy()
        elif rule == "isolated":
            A_new = Abar.copy()
        elif rule == "network":
            A_new = lookahead_A(labels, P1, Pe, sel, dens)
        else:
            raise ValueError(f"unknown fallback rule {rule!r}")
        for s, d in dens.items():
            A_new[pos[s]] = max(d, 0.0)
        A = A_new

    return seen[-1], config.ITER["max_passes"], score(seen[-1], conn, key)


# --------------------------------------------------------------------------- #
# experiments
# --------------------------------------------------------------------------- #
def exp_astar(mats):
    print("=" * 72); print("TABLE 6  A_* sensitivity under site-specific Pe"); print("=" * 72)
    rows = []
    for mid in mats:
        conn, key, labels, P1, Pe = load(mid)
        f_best = score(config.BEST_HEUR_REAL[f"M{mid}"], conn, key)
        print(f"\n  M{mid}: best realistic heuristic F={f_best:.6f}")
        picks = {}
        for a in config.A_STAR_SWEEP:
            sel = solve_weighted(mid, labels, P1, Pe, np.full(len(labels), a))
            F = score(sel, conn, key)
            picks[a] = tuple(sel)
            print(f"     A_* = {a:<8}  F={F:.6f}   {100 * F / f_best:5.1f}%")
            rows.append({"matrix": f"M{mid}", "A_star": a, "F": round(F, 6),
                         "pct_of_best": round(100 * F / f_best, 2),
                         "sites": " ".join(map(str, sel))})
        print(f"     -> {len(set(picks.values()))} distinct designs over the sweep")
    out = config.RUNS_DIR / "astar_sweep.csv"
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    print(f"\n  wrote {out}   <- source for Table 6")


def exp_iterated(mats, rules):
    print("\n" + "=" * 72); print("TABLE 7  iterated surrogate under site-specific Pe"); print("=" * 72)
    rows = []
    for mid in mats:
        conn, key, labels, P1, Pe = load(mid)
        Abar = isolated_A(labels, P1, Pe)
        f_best = score(config.BEST_HEUR_REAL[f"M{mid}"], conn, key)
        print(f"\n  === M{mid}   best realistic heuristic F={f_best:.6f}   "
              f"{int((Abar <= 1e-6).sum())}/{len(labels)} candidates collapse in isolation")
        print(f"      {'start':<22}" + "".join(f"{r:>24}" for r in rules))
        for val in config.ITER["starts"]:
            name = "isolated densities" if val is None else f"constant {val}"
            A0 = Abar if val is None else np.full(len(labels), float(val))
            line = f"      {name:<22}"
            for rule in rules:
                sel, upd, F = iterate(mid, A0, rule, Abar, labels, P1, Pe, conn, key)
                line += f"{F:>12.6f} ({upd}) {100 * F / f_best:>6.1f}%"
                rows.append({"matrix": f"M{mid}", "start": name, "fallback": rule,
                             "updates": upd, "F": round(F, 6),
                             "pct_of_best": round(100 * F / f_best, 2),
                             "sites": " ".join(map(str, sel))})
            print(line)
    out = config.RUNS_DIR / "iterated_table.csv"
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    print(f"\n  wrote {out}   <- source for Table 7")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp", choices=["astar", "iterated", "all"], default="all")
    ap.add_argument("--matrix", choices=["1", "2", "both"], default="both")
    ap.add_argument("--fallback", choices=config.ITER["rules"] + ["all"], default="all")
    args = ap.parse_args()

    mats = ["1", "2"] if args.matrix == "both" else [args.matrix]
    rules = config.ITER["rules"] if args.fallback == "all" else [args.fallback]

    for m in mats:
        if not config.quad_dat(m).exists():
            raise SystemExit(f"{config.quad_dat(m)} missing. Run:\n"
                             f"    python -m scripts.prepare_data --matrix {m}")

    config.RUNS_DIR.mkdir(exist_ok=True)
    t0 = time.time()
    if args.exp in ("astar", "all"):
        exp_astar(mats)
    if args.exp in ("iterated", "all"):
        exp_iterated(mats, rules)
    print(f"\ndone in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()